### ISSUE TITLE
Can't download videos when self hosting.

### ISSUE THREAD

**Issue by Rick1029** [BassThatHertz/AudioAndVideoConverter#13]
Self hosting on a raspberry pi 4 running ubuntu 20.04, both transcoding and downloading from youtube do not work. I've verified that the paths to ffmpeg and youtube-dl are correct, and I've installed all requirements. The error messages are below.

Downloading youtube video
>[2020-07-26 16:07:41,451] ERROR in app: Exception on /yt [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.8/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ubuntu/AudioAndVideoConverter/yt.py", line 122, in yt_downloader
    user_ip = request.environ['HTTP_X_FORWARDED_FOR']
KeyError: 'HTTP_X_FORWARDED_FOR'
192.168.0.200 - - [26/Jul/2020 16:07:41] "POST /yt HTTP/1.1" 500 -

Converting to MKV
> 192.168.0.200 - - [26/Jul/2020 16:05:37] "POST / HTTP/1.1" 200 -
192.168.0.200 - - [26/Jul/2020 16:05:37] "POST / HTTP/1.1" 200 -
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'uploads/YMCA_Spider.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf58.29.100
  Duration: 00:01:11.03, start: 0.000000, bitrate: 410 kb/s
    Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p, 460x258 [SAR 1:1 DAR 230:129], 186 kb/s, 25 fps, 25 tbr, 12800 tbn, 50 tbc (default)
    Metadata:
      handler_name    : ISO Media file produced by Google Inc.
    Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 217 kb/s (default)
    Metadata:
      handler_name    : ISO Media file produced by Google Inc.
Output #0, matroska, to 'conversions/YMCA Spider.mkv':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoded_by      : "free-av-tools.com"
    comment         : "free-av-tools.com"
    encoder         : Lavf58.29.100
    Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p, 460x258 [SAR 1:1 DAR 230:129], q=2-31, 186 kb/s, 25 fps, 25 tbr, 1k tbn, 12800 tbc (default)
    Metadata:
      handler_name    : ISO Media file produced by Google Inc.
    Stream #0:1(und): Audio: aac (LC) ([255][0][0][0] / 0x00FF), 48000 Hz, stereo, fltp, 217 kb/s (default)
    Metadata:
      handler_name    : ISO Media file produced by Google Inc.
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (copy)
Press [q] to stop, [?] for help
frame= 1775 fps=0.0 q=-1.0 Lsize=    3538kB time=00:01:11.00 bitrate= 408.2kbits/s speed= 974x    
video:1617kB audio:1885kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 1.042236%
192.168.0.200 - - [26/Jul/2020 16:05:37] "POST / HTTP/1.1" 200 -
[2020-07-26 16:05:37,831] ERROR in app: Exception on /conversions/YMCA Spider.mkv [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.8/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "main.py", line 222, in send_file
    user_ip = request.environ['HTTP_X_FORWARDED_FOR']
KeyError: 'HTTP_X_FORWARDED_FOR'
192.168.0.200 - - [26/Jul/2020 16:05:37] "GET /conversions/YMCA%20Spider.mkv HTTP/1.1" 500 -

**Comment by BassThatHertz** [comment]
I know what the issue is. I'm already in the process of making some changes to the code, so I will also make the changes that will prevent this issue from occurring. This should be done within an hour, I will let you know when I have pushed the changes and then I would like you to re-clone this repository and try again.

**Comment by BassThatHertz** [comment]
Done. Re-clone this repository and follow the instructions [here](https://github.com/BassThatHertz/AudioAndVideoConverter#requirements-for-developersrunning-locally). Let me know if you run into any issyes.

**Comment by Rick1029** [comment]
Working fine now, I've managed to download several mp3's just fine. I did try downloading an hour long mp3 and it has been adding a thumbnail for 20 minutes now, checking htop tells me its at 100% cpu (out of 400), no throttling, just ffmpeg at 100% usage. The file is an mp3 and around 62 megabytes. Terminal outputs many of this message;

>127.0.0.1 - - [27/Jul/2020 18:57:15] "GET /yt-progress/1595875106.txt HTTP/1.0" 304 -

Killing and restarting the process hasn't done anything.

I've just removed the 'embed--thumbnail' option in yt.py for mp3's and waited about five minutes. The ffmpeg process then died, but the webpage still says "Initializing" and the terminal pushes the same message as above.

**Comment by BassThatHertz** [comment]
@Rick1029 I would like you to re-clone and try again as I have just pushed some changes. It's best to be running the same piece of code when diagnosing an issue. If you still have an issue with the hour-long video, let me know and share the link if you don't mind.

**Comment by BassThatHertz** [comment]
Also, uninstall your current installation of youtube-dl using `pip/pip3 uninstall youtube-dl`, then install the latest version by following the instructions [here](https://github.com/ytdl-org/youtube-dl#installation). The version of youtube-dl that was installed with `pip/pip3 install -r requirements.txt` currently has an issue with downloading videos, so I have removed it from requirements.txt
